#!/usr/bin/python
import os
import time
import struct
import sqlite3
import errno
import md5
import ConfigParser
import requests
from string import Template
from xml.etree import ElementTree

API_KEY = "f9793a7c8724e215987be37ba5691f62"
SECRET = "3bb8f2f6f2de806b213cb73f53803815"
ROOT_URL ="https://ws.audioscrobbler.com/2.0/"		#You must use HTTPS for this request


COUNTS_PATH = 'PlayCounts'		# it should be 'Play Counts'
DB_PATH = 'Library.itdb'
LOCAL_DB_PATH = 'db.sqlite3'
CONFIG_PATH = 'config.cfg'
# The difference between the Unix timestamp epoch (1970) and the Mac timestamp epoch (1904)
# should be used for proper timestamps if timestamps will be found in library somewhere
#APPLE_TIME = 2082844800 		
# since there are no proper timestamps, we will have to make some ourselves
# first scrobble will start a week ago
TSTAMP = int(time.time()) - 604800 + 604800
SONG_TEMPLATE = """$title by $artist from $album; $playcount plays"""

def get_credentials():
	config = ConfigParser.RawConfigParser()
	config.read(CONFIG_PATH)
	u = config.get('lastfm', 'username')
	p = config.get('lastfm', 'password')
	return {'username':u, 'password':p}

def authenticate(username,password):
	api_sig = md5.md5("api_key"+API_KEY
		+"method"+"auth.getMobileSession"
		+"password"+password
		+"username"+username
		+SECRET).hexdigest()
	p = {"method":"auth.getMobileSession",
		 "api_key":API_KEY,
		 "username": username,
		 "password":password,
		 "api_sig":api_sig}
	t = requests.post(ROOT_URL, params=p)
	tree = ElementTree.fromstring(t.text)
	key = tree.findall('session/key')
	if key:
		key = key[0].text
	return key

creds = get_credentials()
SESSION_KEY = authenticate(creds['username'], creds['password'])

# these fieldnames are ignored when generating signature for song
IGNORED_FIELDNAMES = ['pid','playcount']

class Song(object):
	"""docstring for Song"""
	def __init__(self, _pid, _artist, _album, _title, _playcount, _timestamp=0):
		super(Song, self).__init__()
		self.api_sig = None
		self.method = None
		self.api_key = API_KEY
		self.pid = _pid
		self.artist = _artist
		self.album = _album
		self.track = _title 			# track title is 'track' for lastfm
		self.playcount = _playcount 	# playcount should indicate how many times song should be scrobbled
										# probably with a new timestamp
		self.timestamp = _timestamp 	# timestamps are handled by Bunch class
		self.sk = SESSION_KEY
		self.generate_signature()

	def generate_signature(self, _method='track.scrobble'):
		# artist[i] (Required) : The artist name.
		# track[i] (Required) : The track name.
		# timestamp[i] (Required) : The time the track started playing,
		# api_key (Required) : A Last.fm API key.
		# api_sig (Required) : A Last.fm method signature. See authentication for more information.
		# sk (Required) : A session key generated by authenticating a user via the authentication protocol. 
		if not self.timestamp:
			return 0
		sig_string = u""
		self.api_sig = None
		self.method = _method
		self.timestamp = str(self.timestamp)
		for key, value in sorted(self.__dict__.items()):
			if key not in IGNORED_FIELDNAMES:
				if value:
					sig_string = sig_string + key + value
		self.method = None
		self.timestamp = int(self.timestamp)
		self.api_sig = md5.md5((sig_string+SECRET).encode('utf-8')).hexdigest()
		return 0

	def scrobble(self, method='track.scrobble'):
		self.method = 'track.scrobble'
		p = {}
		p['api_key'] = API_KEY
		for key, value in self.__dict__.items():
			if value:
				p[key] = value
		response = requests.post(ROOT_URL, params=p)
		self.method = None
		return response

	def __str__(self):
		text_template = Template(SONG_TEMPLATE)
		text = text_template.substitute({"artist":self.artist, "title":self.track, 
										 "album":self.album, "playcount":self.playcount})
		return text


class Bunch(object):
	"""a bunch of songs, 50 max"""
	def __init__(self, songs, start_timestamp):
		self.__songs__ = songs
		for s in self.__songs__:
			s.timestamp = start_timestamp
			start_timestamp+=1
		self.__generate_signature__()

	def __len__(self):
		return len(self.__songs__)

	def __generate_signature__(self):
		query_string = u""
		p = {}
		p['method'] = u'track.scrobble'
		p['api_key'] = API_KEY
		p['sk'] = SESSION_KEY
		for s in self.__songs__:
			i = str(self.__songs__.index(s))
			p['artist[{}]'.format(i)] = s.artist
			p['track[{}]'.format(i)] = s.track
			p['timestamp[{}]'.format(i)] = str(s.timestamp)
			if s.album:
				p['album[{}]'.format(i)] = s.album
		for key, value in sorted(p.items()):
			query_string = query_string + key + value
		query_string = query_string + SECRET
		p['api_sig'] = u""
		p['api_sig'] = md5.md5((query_string).encode('utf-8')).hexdigest()
		p['query_string'] = query_string
		self.params = p

	def scrobble(self):
		del self.params['query_string']
		response = requests.post(ROOT_URL, params=self.params)
		self.method = None
		return response


class LocalDB(object):
	"""docstring for LocalDB"""
	def __init__(self, arg):
		super(LocalDB, self).__init__()
		self.arg = arg

	def create():
		if not check_path(LOCAL_DB_PATH):
			conn = sqlite3.connect(LOCAL_DB_PATH)
			c = conn.cursor()
			conn.close()

	def update_song(song):
		# updates a single song
		# songs removed from iPod should remain in database - they still exist in iTunes
		pass

	def add_song(song):
		pass

def check_path(path):
	return os.path.isfile(path)

def get_counts(path):
	counts = []
	file_size = os.path.getsize(path)
	# first record starts from 96 byte
	# 60 + 36 = 96
	# never use tell(), it lies a lot
	# http://stackoverflow.com/questions/19730875/python-file-tell-gives-wrong-value-location
	pos = 60
	with open(path,'r') as f:
		f.seek(pos)
		while True:
			pos = pos+36
			if pos+4 > file_size:
				break
			else:
				f.seek(pos)
				a = f.read(4)
				i = struct.unpack('<I',a)
				pos = pos + 4
				counts.extend(i)
	return counts

def get_selected_songs(_dbpath, _songs_ids):
	# gets songs info with at least one playcount from library
	# there is no point in getting songs with zero playcounts
	conn = sqlite3.connect(_dbpath)
	c = conn.cursor()
	songs = []
	for n,i in enumerate(_songs_ids):
		phys_order = i[0]
		play_count = i[1]
		c.execute('SELECT pid, artist, album, title FROM item WHERE physical_order == (?)', (str(phys_order),) )
		r = c.fetchone()
		if play_count > 1:
			for i in range (1,play_count+1):
				s = Song(r[0], r[1], r[2], r[3], i)
				songs.append(s)
		else:
			s = Song(r[0], r[1], r[2], r[3], i)
			songs.append(s)
	conn.close()
	return songs

def get_songs_ids(_counts):
	# remove zeroes leaving only songs which were played
	ids = []
	for physical_order, playcount in enumerate(_counts):
		if playcount > 0:
			ids.append((physical_order,playcount))
	return ids

def scrobble_bulk():
	# scrobbles 50 tracks per once
	pass

def get_playcounts_diff():
	# creates diff between two playcount files AND LIBRARIES
	# returns changed/added songs with amount of scrobbles
	pass

def main():
	if not (check_path(COUNTS_PATH) and check_path(DB_PATH) and check_path(CONFIG_PATH)):
		raise OSError(os.strerror(errno.ENOENT))
	counts = get_counts(COUNTS_PATH)
	songs_ids = get_songs_ids(counts)
	songs = get_selected_songs(DB_PATH,songs_ids)
	count = 0
	page = 0

	while page < (len(songs)/50 + 1):
		b = Bunch(songs[page*50:((page+1)*50)-1], TSTAMP)
		resp = b.scrobble()
		if resp.ok:
			tree = ElementTree.fromstring((resp.text).encode('utf-8'))
			status_element = tree.findall('scrobbles')[0]
			status = status_element.attrib
			print "{} tracks scrobbled".format(status['accepted'])
			if len(b) != int(status['accepted']):
				print 'ERROR, page {}, sent {}, accepted {}'.format(page, len(b), status['accepted'])
				raw_input()
				print resp.text
				raw_input()
			else:
				#print '50 tracks uploaded'
				time.sleep(1)
			page = page+1

	print len(songs),'songs', count, 'plays'
	return 0

if __name__ == '__main__':
	main()
